import postgres from 'postgres'

const client = postgres(
    'postgresql://postgres.nmgrlogjrnetqbommmym:u2B0T0FSeGmC6aUR@aws-0-eu-central-1.pooler.supabase.com:6543/postgres'
)

const data = [
    {
        Marke: 'Aigle',
        'Kurzcharakteristik 1': 'Französische Outdoor-Marke mit Fokus auf Wetterfestigkeit',
        'Kurzcharakteristik 2': 'Authentischer Look für Natur und Stadt',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '2,5',
        Design: '2,0',
        Positionierung: '1,5',
        Heritage: '4,5',
        Herkunft: '5,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'AIGNER',
        'Kurzcharakteristik 1': 'Luxusmarke mit Münchner Wurzeln und ikonischem Hufeisen-Logo',
        'Kurzcharakteristik 2': 'Klassische Eleganz mit italienischer Raffinesse',
        'Kurzcharakteristik 3': 'Hochwertige Materialien und präzise Handwerkskunst',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'Alberto',
        'Kurzcharakteristik 1': 'Moderne Hosen mit perfektem Sitz und technischem Anspruch',
        'Kurzcharakteristik 2': 'Innovative Stoffe und smarte Details für Alltag & Business',
        'Kurzcharakteristik 3': 'Deutsche Ingenieurskunst kombiniert mit trendigen Hosen-Styles',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '2,5',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 4,
    },
    {
        Marke: 'Alberto Bike',
        'Kurzcharakteristik 1': 'Funktionale Hosenmode perfekt fürs Fahrrad',
        'Kurzcharakteristik 2': 'Technisch durchdacht für höchste Performance auf demCity-Bike',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '1,5',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'Alberto Golf',
        'Kurzcharakteristik 1': 'Funktionale Golfmode mit sportlich-elegantem Stil',
        'Kurzcharakteristik 2': 'Technisch durchdacht für höchste Performance auf dem Green',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '3,0',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'ALPHA INDUSTRIES',
        'Kurzcharakteristik 1': 'Authentische Military-Looks mit Kultstatus',
        'Kurzcharakteristik 2': 'Ursprünglich für das US-Militär entwickelt, heute urbaner Klassiker',
        'Kurzcharakteristik 3': 'Robuste Materialien, klare Linien, ikonisches Flight Jacket',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'Armani Exchange',
        'Kurzcharakteristik 1': 'Jung, urban und trendbewusst – Armani für die neue Generation',
        'Kurzcharakteristik 2': 'Streetstyle mit italienischer Eleganz',
        'Kurzcharakteristik 3': 'Modisch, expressiv und zugänglich zugleich',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '3,5',
        Positionierung: '3,0',
        Heritage: '3,5',
        Herkunft: '1,0',
        Bekanntheit: '4,0',
        Umsatz: 1,
    },
    {
        Marke: 'Baldessarini',
        'Kurzcharakteristik 1': 'Luxuriöse Herrenmode mit Reife und Charakter',
        'Kurzcharakteristik 2': 'Stilvolle Looks für Männer, die wissen, was sie wollen',
        'Kurzcharakteristik 3': 'Deutsche Marke mit internationalem Anspruch',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '4,0',
        Heritage: '3,5',
        Herkunft: '2,0',
        Bekanntheit: '3,0',
        Umsatz: 4,
    },
    {
        Marke: 'Baracuta',
        'Kurzcharakteristik 1': 'Britischer Kult mit dem legendären G9 Harrington Jacket',
        'Kurzcharakteristik 2': 'Smart Casual mit Ivy-League-Flair',
        'Kurzcharakteristik 3': 'Tradition trifft auf zeitlose Coolness',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '5,0',
        Bekanntheit: '2,5',
        Umsatz: 3,
    },
    {
        Marke: 'Barbour',
        'Kurzcharakteristik 1': 'Britischer Country-Stil mit wetterfester Funktion',
        'Kurzcharakteristik 2': 'Ikonische Wachsmäntel und kernige Hemden für Stadt und Natur',
        'Kurzcharakteristik 3': 'Tradition, Qualität und Outdoor-Kompetenz seit Generationen',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '1,5',
        Positionierung: '2,0',
        Heritage: '5,0',
        Herkunft: '5,0',
        Bekanntheit: '3,5',
        Umsatz: 5,
    },
    {
        Marke: 'Belstaff',
        'Kurzcharakteristik 1': 'Britischer Luxus mit Wurzeln im Motorsport',
        'Kurzcharakteristik 2': 'Robuste Leder- und Wachsjacken mit ikonischem Design',
        'Kurzcharakteristik 3': 'Abenteuerlich, authentisch, unverwüstlich',
        Preis: '4,0',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '4,5',
        Herkunft: '1,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'Ben Sherman',
        'Kurzcharakteristik 1': 'Britischer Mod-Klassiker mit grafischem Anspruch',
        'Kurzcharakteristik 2': 'Statement-Hemden und smart-casual Looks mit Retro-Flair',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '2,5',
        Heritage: '3,5',
        Herkunft: '5,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'BIRKENSTOCK',
        'Kurzcharakteristik 1': 'Deutsche Ikone für Komfort und ergonomische Fußbetten',
        'Kurzcharakteristik 2': 'Naturverbundene Materialien und nachhaltige Produktion',
        'Kurzcharakteristik 3': 'Funktion trifft auf Zeitgeist und Kultstatus',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '1,0',
        Design: '1,5',
        Positionierung: '2,0',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '4,5',
        Umsatz: 1,
    },
    {
        Marke: 'Blauer. USA',
        'Kurzcharakteristik 1': 'Amerikanischer Police- und Military-Look mit Mode-Attitüde',
        'Kurzcharakteristik 2': 'Authentisch, sportlich, urban',
        'Kurzcharakteristik 3': 'Die legendäre Kult-Lederjacke inspiriert vom US Police-Look',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 2,
    },
    {
        Marke: 'BOB',
        'Kurzcharakteristik 1': 'Italienische Mode mit kreativer Handschrift',
        'Kurzcharakteristik 2': 'Farbenfrohe Details, ausgefallene Stoffe, exzentrisch und charmant',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '2,5',
        Heritage: '2,0',
        Herkunft: '4,0',
        Bekanntheit: '1,5',
        Umsatz: 1,
    },
    {
        Marke: 'Boggi',
        'Kurzcharakteristik 1': 'Italienische Herrenmode mit Business-Fokus und modischem Gespür',
        'Kurzcharakteristik 2': 'Smart Tailoring aus Mailand mit mediterraner Leichtigkeit',
        'Kurzcharakteristik 3': 'Italienische Eleganz für Büro und Afterwork',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '4,0',
        Design: '3,0',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '1,0',
        Bekanntheit: '2,5',
        Umsatz: 3,
    },
    {
        Marke: 'Bogner',
        'Kurzcharakteristik 1': 'Sportlich-luxuriöser Stil mit alpiner Herkunft',
        'Kurzcharakteristik 2': 'Edle Skimode und elegante Freizeitkleidung vom legendären Münchner Willy Bogner',
        'Kurzcharakteristik 3': 'Deutsche Premium-Ästhetik für stilbewusste Aktive, seit 1937 aus München',
        Preis: '4,0',
        Qualität: '4,0',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 3,
    },
    {
        Marke: 'Boss Black',
        'Kurzcharakteristik 1': 'Zeitlose Businesswear mit Fokus auf Eleganz und Qualität',
        'Kurzcharakteristik 2': 'Ideal für formelle Anlässe und gehobene Garderobe',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '3,0',
        Positionierung: '4,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '5,0',
        Umsatz: 5,
    },
    {
        Marke: 'Boss Green',
        'Kurzcharakteristik 1': 'Sportlich-dynamische Linie mit Fokus auf Activewear und Golf',
        'Kurzcharakteristik 2': 'Funktionalität in stilvollem Design',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '2,5',
        Design: '3,0',
        Positionierung: '1,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '5,0',
        Umsatz: 3,
    },
    {
        Marke: 'Boss Orange',
        'Kurzcharakteristik 1': 'Urban Casualwear mit entspannter Attitüde',
        'Kurzcharakteristik 2': 'Kreativ, jung, modern – für stilvolle Freizeit-Looks',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '4,0',
        Positionierung: '2,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '5,0',
        Umsatz: 4,
    },
    {
        Marke: 'Brax',
        'Kurzcharakteristik 1': 'Deutsche Hosenkompetenz mit modischem Anspruch',
        'Kurzcharakteristik 2': 'Smart Casual für Alltag und Business',
        'Kurzcharakteristik 3': 'Bequeme Passformen und hochwertige Verarbeitung',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '3,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'bugatti',
        'Kurzcharakteristik 1': 'Deutsche Lifestylemarke mit europäischem Flair',
        'Kurzcharakteristik 2': 'Stilvolle Mode für Alltag, Reise und Business',
        'Kurzcharakteristik 3': 'Klassisch, tragbar, zuverlässig',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 4,
    },
    {
        Marke: 'CALIDA',
        'Kurzcharakteristik 1': 'Schweizer Wäschemarke mit Fokus auf Komfort und Nachhaltigkeit',
        'Kurzcharakteristik 2': 'Weiche Materialien und perfekte Schnitte für jeden Tag - die perfekte Wäsche!',
        'Kurzcharakteristik 3': 'Umweltbewusst und zeitlos zugleich: Wäsche mit Stil.',
        Preis: '2,5',
        Qualität: '3,5',
        Schwerpunkt: '1,5',
        Design: '1,5',
        Positionierung: '3,0',
        Heritage: '4,5',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'Calvin Klein Underwear',
        'Kurzcharakteristik 1': 'Amerikanische Ikone für minimalistische Coolness',
        'Kurzcharakteristik 2': 'Puristische Ästhetik mit urbanem Sexappeal',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '2,5',
        Schwerpunkt: '1,5',
        Design: '3,0',
        Positionierung: '3,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '4,5',
        Umsatz: 1,
    },
    {
        Marke: 'camel active',
        'Kurzcharakteristik 1': 'Abenteuerlicher Freizeitstil mit Outdoor-Elementen',
        'Kurzcharakteristik 2': 'Robuste Materialien, funktionale Schnitte',
        'Kurzcharakteristik 3': 'Urban Outdoor für aktive Männer',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'Carl Gross',
        'Kurzcharakteristik 1': 'Deutsche Anzugkompetenz mit traditionellem Anspruch',
        'Kurzcharakteristik 2': 'Klassisch-elegante Businessmode in präzisem Schnitt',
        'Kurzcharakteristik 3': 'Stilsicher für formelle Anlässe',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,5',
        Design: '2,5',
        Positionierung: '4,0',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 3,
    },
    {
        Marke: 'CasaModa',
        'Kurzcharakteristik 1': 'Tragbare Herrenmode mit klarem Fokus auf Komfort',
        'Kurzcharakteristik 2': 'Freizeithemden und Strick mit angenehmer Passform',
        'Kurzcharakteristik 3': '',
        Preis: '2,0',
        Qualität: '2,5',
        Schwerpunkt: '2,0',
        Design: '1,5',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'CG Club of Gents',
        'Kurzcharakteristik 1': 'Moderner Ableger von Carl Gross für einen jüngeren Look',
        'Kurzcharakteristik 2': 'Businessmode mit modischem Anspruch und urbanem Twist',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,5',
        Design: '3,0',
        Positionierung: '3,5',
        Heritage: '2,5',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 2,
    },
    {
        Marke: 'CINQUE',
        'Kurzcharakteristik 1': 'Italienisch inspirierte Mode mit urbaner Lässigkeit',
        'Kurzcharakteristik 2': 'Smart Casual für die City – modern, unkompliziert, stilvoll',
        'Kurzcharakteristik 3': '',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '3,0',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 3,
    },
    {
        Marke: 'COLMAR',
        'Kurzcharakteristik 1': 'Italienische Sportswear mit Fokus auf Skimode und Urbanwear',
        'Kurzcharakteristik 2': 'Funktion trifft auf Fashion – clean, sportlich, modern',
        'Kurzcharakteristik 3': 'Kultige Steppjacken mit modischer Linie',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '1,5',
        Heritage: '4,0',
        Herkunft: '5,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'DANIELE FIESOLI',
        'Kurzcharakteristik 1': 'Italienisches Knitwear-Design mit Finesse',
        'Kurzcharakteristik 2': 'Feinstrick, moderne Farben, luxuriöse Materialien',
        'Kurzcharakteristik 3': 'Handwerk trifft modischen Minimalismus',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '3,0',
        Positionierung: '2,5',
        Heritage: '2,5',
        Herkunft: '5,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'DESOTO',
        'Kurzcharakteristik 1': 'Bügelfreie Jersey-Hemden mit Bewegungsfreiheit',
        'Kurzcharakteristik 2': 'Nachhaltig produziert in Europa',
        'Kurzcharakteristik 3': 'Ideal für Business mit Komfortanspruch',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'DIGEL',
        'Kurzcharakteristik 1': 'Deutsche Businessmode mit perfektem Sitz',
        'Kurzcharakteristik 2': 'Mix aus Klassik und modischer Aktualität',
        'Kurzcharakteristik 3': 'Für den modernen Gentleman mit Anspruch',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 3,
    },
    {
        Marke: 'DRESSLER',
        'Kurzcharakteristik 1': 'Traditionelle Anzugmode aus deutscher Fertigung',
        'Kurzcharakteristik 2': 'Hochwertige Materialien, klassische Linien',
        'Kurzcharakteristik 3': 'Maßgeschneiderter Anspruch seit Generationen',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 2,
    },
    {
        Marke: 'dubarry',
        'Kurzcharakteristik 1': 'Irische Outdoor-Marke mit maritimem Erbe',
        'Kurzcharakteristik 2': 'Funktionale Boots und Jacken für Wasser & Land',
        'Kurzcharakteristik 3': 'Robuste Qualität mit elegantem Country-Flair',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,5',
        Design: '1,5',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '5,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'EA7',
        'Kurzcharakteristik 1': 'Sportliche Linie von Emporio Armani mit Fokus auf Performance',
        'Kurzcharakteristik 2': 'Edler Athleisure-Look für Training und Freizeit',
        'Kurzcharakteristik 3': 'Italienisches Design trifft Funktion',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '3,5',
        Positionierung: '1,5',
        Heritage: '3,0',
        Herkunft: '1,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'Emporio Armani',
        'Kurzcharakteristik 1': 'Eleganter Mix aus High Fashion und sportlicher Dynamik',
        'Kurzcharakteristik 2': 'Jüngere, modische Linie von Giorgio Armani',
        'Kurzcharakteristik 3': 'Italienischer Stil mit urbaner Leichtigkeit',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '4,5',
        Design: '3,5',
        Positionierung: '3,5',
        Heritage: '3,5',
        Herkunft: '1,0',
        Bekanntheit: '4,5',
        Umsatz: 2,
    },
    {
        Marke: 'ETERNA',
        'Kurzcharakteristik 1': 'Bügelfreie Businesshemden mit perfektem Sitz',
        'Kurzcharakteristik 2': 'Nachhaltige Produktion mit OEKO-TEX® Standard',
        'Kurzcharakteristik 3': 'Tradition seit 1863 – modern interpretiert',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,5',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'ETON',
        'Kurzcharakteristik 1': 'Schwedische Premium-Hemden mit makelloser Qualität',
        'Kurzcharakteristik 2': 'Perfekte Schnitte und edle Stoffe – Business auf höchstem Niveau',
        'Kurzcharakteristik 3': 'Innovativ, stilvoll, kompromisslos in Qualität',
        Preis: '4,0',
        Qualität: '4,5',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '4,0',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 2,
    },
    {
        Marke: 'Eurex by Brax',
        'Kurzcharakteristik 1': 'Komfort-Hosen mit perfekter Passform und Dehnbund',
        'Kurzcharakteristik 2': 'Fokus auf Bequemlichkeit bei klassischem Look',
        'Kurzcharakteristik 3': 'Ideal für Männer, die Wert auf Funktion & Stil legen',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '2,0',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'Falke',
        'Kurzcharakteristik 1': 'Deutsche Traditionsmarke für Strümpfe & Sportbekleidung',
        'Kurzcharakteristik 2': 'Hohe Qualität, perfekte Passform, sportlicher Komfort',
        'Kurzcharakteristik 3': 'Für Performance wie für Alltag',
        Preis: '3,0',
        Qualität: '4,0',
        Schwerpunkt: '1,0',
        Design: '2,0',
        Positionierung: '5,0',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 3,
    },
    {
        Marke: 'FIL NOIR',
        'Kurzcharakteristik 1': 'Italienisches Hemdenlabel mit Vintage-Flair',
        'Kurzcharakteristik 2': 'Weiche Stoffe, entspannte Schnitte, raffinierte Details',
        'Kurzcharakteristik 3': 'Authentisch, bewusst, traditionsreich',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '2,5',
        Design: '3,0',
        Positionierung: '3,0',
        Heritage: '2,5',
        Herkunft: '5,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'FIRE + ICE',
        'Kurzcharakteristik 1': 'Sportliche Linie von BOGNER mit Fokus auf Skimode und Urbanwear',
        'Kurzcharakteristik 2': 'Funktion und Fashion für Berge und Stadt',
        'Kurzcharakteristik 3': 'Aktiver Look mit modischem Anspruch',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '2,5',
        Design: '3,0',
        Positionierung: '1,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'Floris van Bommel',
        'Kurzcharakteristik 1': 'Niederländische Herrenschuhe mit Charakter',
        'Kurzcharakteristik 2': 'Klassisches Handwerk trifft auf moderne Designideen',
        'Kurzcharakteristik 3': 'Exzentrisch, hochwertig, traditionsreich',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '1,0',
        Design: '3,0',
        Positionierung: '3,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'Fred Perry',
        'Kurzcharakteristik 1': 'Britischer Street-Style mit sportlicher Geschichte',
        'Kurzcharakteristik 2': 'Ikonische Polohemden mit Lorbeerkranz-Logo',
        'Kurzcharakteristik 3': 'Mod-Kultur, Subkultur, Stilbewusstsein',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '2,5',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '5,0',
        Bekanntheit: '3,5',
        Umsatz: 5,
    },
    {
        Marke: 'Fynch-Hatton',
        'Kurzcharakteristik 1': 'Casualwear mit Abenteuergeist und Qualität',
        'Kurzcharakteristik 2': 'Inspiriert von Afrika – maskulin, bodenständig, authentisch',
        'Kurzcharakteristik 3': 'Ideal für Freizeit und moderne Outdoor-Looks',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '2,5',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 2,
    },
    {
        Marke: 'Gant',
        'Kurzcharakteristik 1': 'Amerikanischer Preppy-Stil mit europäischen Einflüssen',
        'Kurzcharakteristik 2': 'Smart Casual für stilbewusste Alltagslooks',
        'Kurzcharakteristik 3': 'Klassische Hemden, Knitwear und Polos mit Ivy-League-Flair',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '2,0',
        Positionierung: '2,5',
        Heritage: '4,0',
        Herkunft: '2,0',
        Bekanntheit: '3,5',
        Umsatz: 3,
    },
    {
        Marke: 'GARDEUR',
        'Kurzcharakteristik 1': 'Perfekte Hosenpassform mit deutscher Präzision',
        'Kurzcharakteristik 2': 'Business- und Freizeit-Looks in hochwertiger Verarbeitung',
        'Kurzcharakteristik 3': 'Zeitlos, tragbar, komfortorientiert',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'GEOX',
        'Kurzcharakteristik 1': 'Atmungsaktive Schuhe mit patentierter Technologie',
        'Kurzcharakteristik 2': 'Funktionalität trifft auf italienischen Stil',
        'Kurzcharakteristik 3': '„Schuhe, die atmen“ – für Alltag, Business und Freizeit',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '1,0',
        Design: '2,5',
        Positionierung: '2,5',
        Heritage: '3,0',
        Herkunft: '5,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'Gran Sasso',
        'Kurzcharakteristik 1': 'Italienisches Strickhandwerk in Perfektion',
        'Kurzcharakteristik 2': 'Edle Materialien und feine Verarbeitung',
        'Kurzcharakteristik 3': 'Zeitlos elegant – von Polos bis Rollkragen',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,0',
        Heritage: '4,0',
        Herkunft: '5,0',
        Bekanntheit: '2,5',
        Umsatz: 2,
    },
    {
        Marke: 'HACKETT',
        'Kurzcharakteristik 1': 'Britischer Gentleman-Stil mit sportlicher Note',
        'Kurzcharakteristik 2': 'Traditionelle Eleganz neu interpretiert',
        'Kurzcharakteristik 3': 'Londoner Heritage trifft auf moderne Maskulinität',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '4,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '3,5',
        Herkunft: '5,0',
        Bekanntheit: '3,0',
        Umsatz: 2,
    },
    {
        Marke: 'handstich',
        'Kurzcharakteristik 1': 'Premiumjacken mit sportlich-edler Handschrift',
        'Kurzcharakteristik 2': 'Detailverliebt, technisch, stilvoll',
        'Kurzcharakteristik 3': 'Für moderne Entdecker und urbane Outdoor-Typen',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '3,5',
        Heritage: '2,5',
        Herkunft: '4,0',
        Bekanntheit: '1,5',
        Umsatz: 1,
    },
    {
        Marke: 'HANRO',
        'Kurzcharakteristik 1': 'Schweizer Wäscheluxus mit puristischer Ästhetik',
        'Kurzcharakteristik 2': 'Weiche Stoffe, perfekte Passform, zeitlose Eleganz',
        'Kurzcharakteristik 3': 'Loungewear auf höchstem Niveau',
        Preis: '4,0',
        Qualität: '4,5',
        Schwerpunkt: '1,5',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'Hechter Paris',
        'Kurzcharakteristik 1': 'Französische Herrenmode mit urbanem Chic',
        'Kurzcharakteristik 2': 'Sportlich-elegant, tragbar, dezent modern',
        'Kurzcharakteristik 3': 'Für Männer mit Sinn für französische Klassik',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '3,0',
        Heritage: '4,0',
        Herkunft: '1,0',
        Bekanntheit: '3,0',
        Umsatz: 4,
    },
    {
        Marke: 'Hiltl',
        'Kurzcharakteristik 1': 'Perfekte Herrenhosen aus deutscher Schneidertradition',
        'Kurzcharakteristik 2': 'Exakte Passform, beste Materialien, langlebiger Tragekomfort',
        'Kurzcharakteristik 3': 'Hochwertige Verarbeitung seit Generationen',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '3,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '2,0',
        Bekanntheit: '2,5',
        Umsatz: 3,
    },
    {
        Marke: 'HOM',
        'Kurzcharakteristik 1': 'Französische Unterwäsche mit stilvoller Funktion',
        'Kurzcharakteristik 2': 'Komfort, Passform, Eleganz – für Tag und Nacht',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '1,5',
        Design: '2,5',
        Positionierung: '3,0',
        Heritage: '3,5',
        Herkunft: '5,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'HUGO',
        'Kurzcharakteristik 1': 'Trendige Linie von BOSS – jung, kreativ, modern',
        'Kurzcharakteristik 2': 'Mode mit Fokus auf Individualität und urbanen Stil',
        'Kurzcharakteristik 3': 'Modisch-progressive Schnitte und starke Farbkonzepte',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '3,5',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '4,5',
        Umsatz: 3,
    },
    {
        Marke: 'John Smedley',
        'Kurzcharakteristik 1': 'Feinste Strickwaren aus England seit 1784',
        'Kurzcharakteristik 2': 'Luxuriös, zeitlos, aus Sea Island Cotton und Merinowolle',
        'Kurzcharakteristik 3': 'Tradition und Understatement auf höchstem Niveau',
        Preis: '4,0',
        Qualität: '4,5',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '5,0',
        Herkunft: '5,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'Joop!',
        'Kurzcharakteristik 1': 'Deutsche Designermarke mit markantem Modebewusstsein',
        'Kurzcharakteristik 2': 'Urban, selbstbewusst, modisch-elegant',
        'Kurzcharakteristik 3': 'Für Männer mit Stil und Attitüde',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,5',
        Design: '3,5',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '4,0',
        Umsatz: 5,
    },
    {
        Marke: 'Karl Lagerfeld',
        'Kurzcharakteristik 1': 'Modelegende trifft auf futuristischen Stil',
        'Kurzcharakteristik 2': 'Monochrom, ikonisch, avantgardistisch',
        'Kurzcharakteristik 3': 'Streetstyle mit Couture-Attitüde',
        Preis: '3,5',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '3,5',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '1,0',
        Bekanntheit: '4,5',
        Umsatz: 3,
    },
    {
        Marke: 'K-WAY',
        'Kurzcharakteristik 1': 'Französische Funktionsjacken mit Kultstatus',
        'Kurzcharakteristik 2': 'Leicht, wasserfest, faltbar – perfekt für unterwegs',
        'Kurzcharakteristik 3': 'Urban Outdoor mit Retro-Charme',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '1,5',
        Heritage: '3,5',
        Herkunft: '5,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'LACOSTE',
        'Kurzcharakteristik 1': 'Französischer Sportswear-Klassiker mit Kultstatus',
        'Kurzcharakteristik 2': 'Erfinder des Poloshirts mit Krokodil-Logo',
        'Kurzcharakteristik 3': 'Casual Chic mit sportlicher Eleganz',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '2,0',
        Positionierung: '2,5',
        Heritage: '4,5',
        Herkunft: '5,0',
        Bekanntheit: '4,5',
        Umsatz: 2,
    },
    {
        Marke: 'Lee',
        'Kurzcharakteristik 1': 'Authentische Denimwear mit US-Tradition',
        'Kurzcharakteristik 2': 'Robuste Jeansmode für Arbeit und Freizeit',
        'Kurzcharakteristik 3': 'Casual, funktional, ikonisch',
        Preis: '2,0',
        Qualität: '2,5',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '2,0',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '4,0',
        Umsatz: 1,
    },
    {
        Marke: 'LLOYD',
        'Kurzcharakteristik 1': 'Deutsche Herrenschuhe mit Komfort und Stil',
        'Kurzcharakteristik 2': 'Die Schuhe mit der roten Sohle als Markenzeichen',
        'Kurzcharakteristik 3': 'Business, Casual und Sneaker – immer hochwertig',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '1,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'Maerz',
        'Kurzcharakteristik 1': 'Strickkompetenz aus München seit 1920',
        'Kurzcharakteristik 2': 'Merinowolle, klassische Passformen, langlebig',
        'Kurzcharakteristik 3': 'Qualität trifft auf Understatement',
        Preis: '3,0',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '2,5',
        Heritage: '4,5',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 3,
    },
    {
        Marke: "Marc O'Polo",
        'Kurzcharakteristik 1': 'Urban Natural Style – skandinavisch inspiriert, modern umgesetzt',
        'Kurzcharakteristik 2': 'Natürliche Materialien, klare Linien',
        'Kurzcharakteristik 3': 'Casualwear mit Premium-Attitüde',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '2,5',
        Heritage: '3,5',
        Herkunft: '2,0',
        Bekanntheit: '4,0',
        Umsatz: 3,
    },
    {
        Marke: "Mason's",
        'Kurzcharakteristik 1': 'Italienische Hosenmarke mit Military-Flair',
        'Kurzcharakteristik 2': 'Markante Details, hochwertige Stoffe',
        'Kurzcharakteristik 3': 'Eleganter Utility-Look für Alltag & Business',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '3,0',
        Design: '3,0',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '5,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'Mey',
        'Kurzcharakteristik 1': 'Hochwertige Wäsche mit perfekter Passform und Nachhaltigkeit',
        'Kurzcharakteristik 2': 'Alltagstauglich, bequem, fair produziert',
        'Kurzcharakteristik 3': 'Moderne Klassiker mit Wohlfühlfaktor',
        Preis: '3,0',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 3,
    },
    {
        Marke: 'Milestone',
        'Kurzcharakteristik 1': 'Jackenspezialist mit urbanem Anspruch',
        'Kurzcharakteristik 2': 'Funktionale Details, modisches Design',
        'Kurzcharakteristik 3': 'Für Männer mit Sinn für Qualität und Look',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '3,0',
        Positionierung: '2,5',
        Heritage: '4,0',
        Herkunft: '2,0',
        Bekanntheit: '2,0',
        Umsatz: 3,
    },
    {
        Marke: 'MUSTANG',
        'Kurzcharakteristik 1': 'Authentische Jeansmarke aus Deutschland',
        'Kurzcharakteristik 2': 'Robuste Qualität, klassische Passformen',
        'Kurzcharakteristik 3': 'Denim für Individualisten seit 1932',
        Preis: '2,0',
        Qualität: '2,0',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'N.Z.A.',
        'Kurzcharakteristik 1': 'New Zealand Auckland – Sportswear mit Abenteuergeist',
        'Kurzcharakteristik 2': 'Farbenfroh, robust, inspiriert von Natur & Reise',
        'Kurzcharakteristik 3': 'Casualwear mit Outdoor-Charakter',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '2,0',
        Heritage: '2,0',
        Herkunft: '2,0',
        Bekanntheit: '2,0',
        Umsatz: 2,
    },
    {
        Marke: 'NAPAPIJRI',
        'Kurzcharakteristik 1': 'Italienisches Outdoorlabel mit norwegischer Seele',
        'Kurzcharakteristik 2': 'Jacken, Polos & Rucksäcke für Urban Explorer',
        'Kurzcharakteristik 3': 'Expedition trifft Design',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '2,5',
        Design: '3,0',
        Positionierung: '1,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'NORTH SAILS',
        'Kurzcharakteristik 1': 'Nachhaltige Sportswear mit maritimer DNA',
        'Kurzcharakteristik 2': 'Funktionale Segelmode trifft moderne Streetwear',
        'Kurzcharakteristik 3': 'Mode mit ökologischem Bewusstsein',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '1,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 1,
    },
    {
        Marke: 'Novila',
        'Kurzcharakteristik 1': 'Edle Nachtwäsche „Made in Germany“',
        'Kurzcharakteristik 2': 'Weich, hochwertig, zeitlos – Komfort auf höchstem Niveau',
        'Kurzcharakteristik 3': '',
        Preis: '3,0',
        Qualität: '4,0',
        Schwerpunkt: '1,5',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 2,
    },
    {
        Marke: 'Olaf Benz',
        'Kurzcharakteristik 1': 'Premium-Unterwäsche mit perfektem Sitz',
        'Kurzcharakteristik 2': 'Körpernah, glatt, funktionell – Made in Germany',
        'Kurzcharakteristik 3': 'Moderne Ästhetik trifft auf Hightech-Materialien',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '1,5',
        Design: '3,0',
        Positionierung: '3,0',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'Olymp',
        'Kurzcharakteristik 1': 'Hemden-Experte aus Deutschland mit kompromissloser Qualität',
        'Kurzcharakteristik 2': 'Bügelfrei, business-tauglich, zeitlos modern',
        'Kurzcharakteristik 3': 'Klassiker für Büro, Event und Alltag',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '4,0',
        Heritage: '4,0',
        Herkunft: '2,0',
        Bekanntheit: '3,5',
        Umsatz: 5,
    },
    {
        Marke: 'OLYMP Signature',
        'Kurzcharakteristik 1': 'Premiumlinie von OLYMP – höchste Qualität und edle Details',
        'Kurzcharakteristik 2': 'Exklusive Stoffe, maßinspirierte Passform',
        'Kurzcharakteristik 3': 'Für Männer mit höchsten Ansprüchen an Businesshemden',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '2,5',
        Positionierung: '4,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'Panama Jack',
        'Kurzcharakteristik 1': 'Robuste Boots und Outdoor-Schuhe aus Spanien',
        'Kurzcharakteristik 2': 'Wetterfest, langlebig, komfortabel',
        'Kurzcharakteristik 3': 'Für Abenteuer und Urban Outdoor',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '1,0',
        Design: '1,5',
        Positionierung: '2,0',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'PARAJUMPERS',
        'Kurzcharakteristik 1': 'Performancejacken mit Expeditionscharakter',
        'Kurzcharakteristik 2': 'Funktionalität auf höchstem Niveau, ikonische Details',
        'Kurzcharakteristik 3': 'Für extreme Bedingungen und urbanes Leben',
        Preis: '4,0',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '3,0',
        Positionierung: '1,5',
        Heritage: '2,5',
        Herkunft: '5,0',
        Bekanntheit: '3,0',
        Umsatz: 2,
    },
    {
        Marke: 'Pepe Jeans',
        'Kurzcharakteristik 1': 'Britischer Denim-Style mit jugendlicher Attitüde',
        'Kurzcharakteristik 2': 'Casualwear mit modischen Akzenten',
        'Kurzcharakteristik 3': 'London Spirit trifft auf Alltagstauglichkeit',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '3,0',
        Design: '3,0',
        Positionierung: '2,0',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 1,
    },
    {
        Marke: 'PEUTEREY',
        'Kurzcharakteristik 1': 'Italienische Jackenspezialisten mit urbanem Anspruch',
        'Kurzcharakteristik 2': 'Die Jacke. Klare Schnitte, Hightech-Stoffe, City-tauglich',
        'Kurzcharakteristik 3': 'Jacken aus Italien. Eleganz trifft Funktion',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '3,0',
        Positionierung: '2,0',
        Heritage: '3,0',
        Herkunft: '5,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'Pierre Cardin',
        'Kurzcharakteristik 1': 'Französische Designermode mit internationaler Strahlkraft',
        'Kurzcharakteristik 2': 'Zeitloser Stil für Business und gepflegte Freizeit',
        'Kurzcharakteristik 3': 'Erreichbarer Luxus für jeden Tag',
        Preis: '2,5',
        Qualität: '2,5',
        Schwerpunkt: '4,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,0',
        Herkunft: '5,0',
        Bekanntheit: '4,0',
        Umsatz: 4,
    },
    {
        Marke: 'Polo Ralph Lauren',
        'Kurzcharakteristik 1': 'Amerikanischer Preppy-Stil mit weltweitem Kultstatus',
        'Kurzcharakteristik 2': 'Ikonische Polos, College-Optik, gehobene Freizeitmode',
        'Kurzcharakteristik 3': 'Tradition, Klasse und Lebensstil in einem Look',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '5,0',
        Design: '2,0',
        Positionierung: '2,5',
        Heritage: '3,5',
        Herkunft: '2,0',
        Bekanntheit: '5,0',
        Umsatz: 5,
    },
    {
        Marke: 'Prime Shoes',
        'Kurzcharakteristik 1': 'Klassische Rahmengenähte Herrenschuhe',
        'Kurzcharakteristik 2': 'Deutsche Qualität, stilvoll und langlebig',
        'Kurzcharakteristik 3': 'Für Business und besondere Anlässe',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '1,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'RAGMAN',
        'Kurzcharakteristik 1': 'Casualwear mit Komfort und Qualität',
        'Kurzcharakteristik 2': 'Strick, Polos und Basics für jeden Tag',
        'Kurzcharakteristik 3': 'Unkompliziert, gepflegt, tragbar',
        Preis: '2,0',
        Qualität: '2,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '2,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '2,0',
        Umsatz: 2,
    },
    {
        Marke: 'Replay',
        'Kurzcharakteristik 1': 'Italienisches Denimlabel mit urbanem Edge',
        'Kurzcharakteristik 2': 'Waschungen, Used-Effekte, moderne Schnitte',
        'Kurzcharakteristik 3': 'Jeansmode mit rebellischer Attitüde',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '3,5',
        Positionierung: '2,0',
        Heritage: '3,5',
        Herkunft: '5,0',
        Bekanntheit: '3,5',
        Umsatz: 3,
    },
    {
        Marke: 'rosso e nero',
        'Kurzcharakteristik 1': 'Italienische Schuhe mit modernem Business-Twist',
        'Kurzcharakteristik 2': 'Formell und doch leger – für smarte Auftritte',
        'Kurzcharakteristik 3': 'Italienische Manufaktur-Qualität. Einzig in Preis/Leistung',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '3,0',
        Heritage: '2,5',
        Herkunft: '5,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'Roy Robson',
        'Kurzcharakteristik 1': 'Smarte Anzüge & Businessmode mit modernem Flair',
        'Kurzcharakteristik 2': 'Deutsche Anzug-Marke mit internationaler Ausrichtung',
        'Kurzcharakteristik 3': 'Ein Anzug der Passform, Funktion und Stil vereint',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '3,0',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '2,0',
        Bekanntheit: '2,5',
        Umsatz: 4,
    },
    {
        Marke: 'SAVE THE DUCK',
        'Kurzcharakteristik 1': 'Vegane Jackenmarke mit Funktion & Nachhaltigkeit',
        'Kurzcharakteristik 2': 'Tierfrei, technisch, urban',
        'Kurzcharakteristik 3': '„No Duck Down“ – verantwortungsvolle Outdoor-Mode',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '3,0',
        Positionierung: '1,5',
        Heritage: '2,0',
        Herkunft: '5,0',
        Bekanntheit: '2,5',
        Umsatz: 2,
    },
    {
        Marke: 'Schiesser',
        'Kurzcharakteristik 1': 'Deutsche Wäscheklassiker seit 1875',
        'Kurzcharakteristik 2': 'Funktional, bequem, langlebig – Qualität für jeden Tag',
        'Kurzcharakteristik 3': 'Tradition trifft Moderne',
        Preis: '2,5',
        Qualität: '3,5',
        Schwerpunkt: '2,0',
        Design: '1,5',
        Positionierung: '2,5',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'Seidensticker',
        'Kurzcharakteristik 1': 'Hemdenmarke mit Tradition und Innovationsgeist',
        'Kurzcharakteristik 2': 'Bügelfrei, stilvoll, modern klassisch',
        'Kurzcharakteristik 3': 'Seit 1919 – Qualität aus Bielefeld',
        Preis: '2,5',
        Qualität: '3,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,5',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 2,
    },
    {
        Marke: 'Stenströms',
        'Kurzcharakteristik 1': 'Schwedische Premium-Hemden mit makelloser Verarbeitung',
        'Kurzcharakteristik 2': 'Das schwedische Hemd. Edle Stoffe, klassische Eleganz, luxuriöse Details',
        'Kurzcharakteristik 3': 'Das edle Hema aus Schweden. Businessmode mit nordischem Stil',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,5',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 2,
    },
    {
        Marke: 'Strellson',
        'Kurzcharakteristik 1': 'Schweizer Marke für smarte Business- und Casualwear',
        'Kurzcharakteristik 2': 'Geradlinig, urban, international',
        'Kurzcharakteristik 3': 'Für Männer mit Haltung und Stil',
        Preis: '3,0',
        Qualität: '3,0',
        Schwerpunkt: '4,0',
        Design: '3,0',
        Positionierung: '3,5',
        Heritage: '3,0',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 4,
    },
    {
        Marke: 'Timberland',
        'Kurzcharakteristik 1': 'Robuste Boots mit amerikanischer Outdoor-DNA',
        'Kurzcharakteristik 2': 'Klassiker in Gelb – langlebig, markant und wetterfest',
        'Kurzcharakteristik 3': 'Mode für Natur, Stadt und Straße',
        Preis: '3,0',
        Qualität: '3,5',
        Schwerpunkt: '3,0',
        Design: '2,5',
        Positionierung: '2,0',
        Heritage: '4,0',
        Herkunft: '4,0',
        Bekanntheit: '4,5',
        Umsatz: 1,
    },
    {
        Marke: 'Tommy Hilfiger',
        'Kurzcharakteristik 1': 'Amerikanischer Preppy-Stil mit weltweiter Bekanntheit',
        'Kurzcharakteristik 2': 'Ikonische Farben, sportlich-elegant',
        'Kurzcharakteristik 3': 'Casualwear mit Ivy-League-Attitüde',
        Preis: '3,0',
        Qualität: '2,5',
        Schwerpunkt: '5,0',
        Design: '3,0',
        Positionierung: '2,5',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '4,5',
        Umsatz: 3,
    },
    {
        Marke: 'tramarossa',
        'Kurzcharakteristik 1': 'Italienische Luxusjeans mit Maßanspruch',
        'Kurzcharakteristik 2': 'Die italienische Jeans. Individuell, handgefertigt, edle Stoffe',
        'Kurzcharakteristik 3': 'Die italienische Edel-Jeans mit persönlicher Gravur',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '3,0',
        Design: '3,0',
        Positionierung: '2,5',
        Heritage: '3,0',
        Herkunft: '5,0',
        Bekanntheit: '2,0',
        Umsatz: 1,
    },
    {
        Marke: 'van Laack',
        'Kurzcharakteristik 1': 'Hemden mit Maßanspruch und luxuriösen Details',
        'Kurzcharakteristik 2': 'Das Premiumhemd. Feine Stoffe, perfekte Passformen, edle Knöpfe',
        'Kurzcharakteristik 3': 'Das Premiumhemd aus Deutschland seit 1881',
        Preis: '3,5',
        Qualität: '4,0',
        Schwerpunkt: '2,0',
        Design: '2,0',
        Positionierung: '3,5',
        Heritage: '4,5',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 2,
    },
    {
        Marke: 'Windsor',
        'Kurzcharakteristik 1': 'Deutsche Luxusmarke für Business- und Casualwear',
        'Kurzcharakteristik 2': 'Zurückhaltender Stil, exzellente Stoffe',
        'Kurzcharakteristik 3': 'Zeitlose Eleganz für jeden Tag',
        Preis: '3,5',
        Qualität: '3,5',
        Schwerpunkt: '4,0',
        Design: '2,5',
        Positionierung: '3,5',
        Heritage: '3,5',
        Herkunft: '4,0',
        Bekanntheit: '3,0',
        Umsatz: 1,
    },
    {
        Marke: 'WOOLRICH',
        'Kurzcharakteristik 1': 'Outdoorjacken mit amerikanischer Geschichte',
        'Kurzcharakteristik 2': 'Funktion trifft Heritage – Parkas mit Kultstatus',
        'Kurzcharakteristik 3': 'Robuste Materialien, ikonische Silhouetten',
        Preis: '4,0',
        Qualität: '4,0',
        Schwerpunkt: '2,5',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '3,5',
        Umsatz: 3,
    },
    {
        Marke: 'Wrangler',
        'Kurzcharakteristik 1': 'Authentische Denimwear aus den USA',
        'Kurzcharakteristik 2': 'Lässiger Western-Style mit funktionaler Ausrichtung',
        'Kurzcharakteristik 3': "Cowboys, Rodeo & Rock 'n' Roll",
        Preis: '2,0',
        Qualität: '2,5',
        Schwerpunkt: '3,0',
        Design: '2,0',
        Positionierung: '2,0',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '4,0',
        Umsatz: 1,
    },
    {
        Marke: 'Zimmerli',
        'Kurzcharakteristik 1': 'Schweizer Wäscheluxus seit 1871',
        'Kurzcharakteristik 2': 'Feinste Materialien, makellose Verarbeitung',
        'Kurzcharakteristik 3': '„The world’s finest underwear“',
        Preis: '4,5',
        Qualität: '5,0',
        Schwerpunkt: '1,5',
        Design: '1,5',
        Positionierung: '3,5',
        Heritage: '5,0',
        Herkunft: '4,0',
        Bekanntheit: '2,5',
        Umsatz: 2,
    },
]

const getVal = (ob: any, val: string) => {
    if (!ob) return null
    return ob[val] ? parseFloat(ob[val].toString().replace(',', '.')) : null
}

async function main() {
    await client.begin(async (sql) => {
        for (const brand of data) {
            const updateQ = {
                name: brand.Marke,
                price: getVal(brand, 'Preis'),
                quality: getVal(brand, 'Qualität'),
                focus: getVal(brand, 'Schwerpunkt'),
                design: getVal(brand, 'Design'),
                positioning: getVal(brand, 'Positionierung'),
                heritage: getVal(brand, 'Heritage'),
                origin: getVal(brand, 'Herkunft'),
                fame: getVal(brand, 'Bekanntheit'),
                sales_volume: getVal(brand, 'Umsatz'),
            }
            const [ins] =
                await sql`insert into brands ${sql(updateQ, 'name', 'price', 'quality', 'focus', 'design', 'positioning', 'heritage', 'origin', 'fame', 'sales_volume')} returning *`

            const characteristics = [
                brand['Kurzcharakteristik 1'],
                brand['Kurzcharakteristik 2'],
                brand['Kurzcharakteristik 3'],
            ]

            for (const character of characteristics) {
                if (!character) continue
                const insChar = {
                    brand_id: ins.id,
                    value: character,
                }
                await sql`insert into characteristics ${sql(insChar)}`
            }
        }
    })
    await client.end()
}

main()
